../17.0.2-17.32.13/Dockerfile_x86

   ./restare.etc/newfolder-etc1/...
     ./then whoami admin? ==Y
             do System.Windows.Writeline(" the windows itsnot one user, please intro user and  password")
    end
   end
